# Generated by Django 4.1.7 on 2023-06-20 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 6, 20, 19, 28, 53, 919783))),
            ],
        ),
    ]
